name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
          extensions: gd, zip, xml, mbstring, ctype, fileinfo, json, dom
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          working-directory: "_protected"
          composer-options: "--prefer-dist --no-progress --classmap-authoritative"
      - run: php _protected/init --env=Production --overwrite=All
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.opsjar.site
          username: git@opsjar.site
          password: ZkW34fMg2fKEbf6cwDDPt7pr
          timeout: 600000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            _protected/common/config/main-local.php
            _protected/backend/config/main-local.php
            _protected/backend/web/assets/**
            assets/**
            deploy.js
