name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
          extensions: gd, zip, xml, mbstring, ctype, fileinfo, json, dom
          coverage: none
      - run: cd _protected
      - uses: ramsey/composer-install@v3
        with:
          working-directory: "_protected"
          composer-options: "--prefer-dist --no-progress --classmap-authoritative"
      - run: php init --env=Production --overwrite=All
